plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.0'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {

    // Build REST APIs
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // Database operations using Hibernate/JPA
   // implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // Bean validation (@Valid, @NotBlank, etc.)
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // Reduces boilerplate code (getters, setters, constructors)
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // MySQL database driver
    //runtimeOnly 'com.mysql:mysql-connector-j'

    // Testing support
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
    useJUnitPlatform()
}